name: poincare
channels:
- anaconda
- pytorch
- defaults
dependencies:
- pip
- python=3.6
- nltk
- scikit-learn
- pytorch=1.0.0
- pandas
- h5py
- cython
- tqdm
- pip:
  - git+https://github.com/facebookresearch/fvcore.git
  - git+https://github.com/facebookresearch/hypernymysuite.git
